# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2de10b8031f423c3f2ef029949a9aec99f941c45536d81f50de65e463a81a7bb52954495a04bd0ead280a5e23a090febd1761c44a7b8ad9a85308c7e597ea30

test:
  secret_key_base: 9e36635941d0fb922e504cb2fe279e1691dd35d0a8a776d0dfac898ac5c6f62ca04b63450ebee184b8851d47670bcd7e38224d2aae9c67c2fdbc8b838d01588f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
